trigger:
  - change-UI

pool:
  name: 'Default'

steps:
- checkout: self

- task: UseDotNet@2
  displayName: 'Install .NET 6'
  inputs:
    packageType: 'sdk'
    version: '6.0.x'

- script: dotnet restore EfPractice/EfPractice.csproj
  displayName: 'Restore dependencies'

- script: dotnet build EfPractice/EfPractice.csproj --configuration Release --no-restore
  displayName: 'Build'

- script: dotnet publish EfPractice/EfPractice.csproj --configuration Release --output $(Build.ArtifactStagingDirectory) --no-build
  displayName: 'Publish'

- task: ArchiveFiles@2
  displayName: 'Zip Published Output'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    ArtifactName: 'drop'